- repo: https://github.com/troian/pre-commit-golang
  sha: HEAD
  hooks:
    -   id: go-build

- repo: git://github.com/korjavin/pre-commit-golang
  sha: HEAD
  hooks:
    # - id: go-fmt
    # - id: go-vet
    # - id: go-lint
    - id: golangci-lint
    - id: gometalinter
    - id: go-critic
