# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/whalesburg/go-influx
    steps:
      - checkout
      - run: go build -v
  test:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/whalesburg/go-influx
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test ./... -v -run=^Test
      - run: go test ./... -v -run=^Test -race
      - run: go test ./... -bench=. -benchmem -run=^Benchmark
  linter1:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/whalesburg/go-influx
    steps:
      - checkout
      - run: go get -u github.com/alecthomas/gometalinter
      - run: gometalinter --install
      - run: gometalinter --config=gometalinter.json
  linter2:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/whalesburg/go-influx
    steps:
      - run: go get -u github.com/go-critic/go-critic/...
      - run: $GOPATH/bin/gocritic check-project -withExperimental -disable commentedOutCode,hugeParam,singleCaseSwitch . || true

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - linter1:
          requires:
            - test
      - linter2:
          requires:
            - test
